# Generated by Django 3.1.7 on 2021-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
