# Generated by Django 3.1.7 on 2021-09-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailyentry_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='added',
            new_name='add',
        ),
    ]
