# Generated by Django 3.1.7 on 2021-09-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210926_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='opening',
            new_name='close',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
